### ISSUE TITLE
PHP SDK Documentation

### ISSUE THREAD

**Issue by phsanzovo** [inspetor/inspetor-php#8]

**Comment by pearsonhenri** [comment]
Current game plan:
- Convert PHP comments to Markdown files (use something like [this](https://github.com/michelf/php-markdown))
- Generate full docs hosting with [Slate](https://github.com/lord/slate)
- Describe full integration workflow:
  - Instantiation of Inspetor client
  - Where to track essential entities (creation, updates, deletions)
